### ISSUE TITLE
Can't build on latest macOS

### ISSUE THREAD

**Issue by ruipacheco** [sociomantic/libdrizzle-redux#321]
```
~/Desktop/libdrizzle-redux · (v6.x.x)
⟩ ./bootstrap.sh 
unknown
`/opt/local/bin/glibtoolize --copy --install --force' 
glibtoolize: found 'configure.ac'
glibtoolize: export M4='/usr/bin/m4'
glibtoolize: ac_aux_dir='build/build-aux'
glibtoolize: ltdl mode=''
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build/build-aux'.
glibtoolize: cp -f /opt/local/share/libtool/build-aux/config.guess build/build-aux
glibtoolize: cp -f /opt/local/share/libtool/build-aux/config.sub build/build-aux
glibtoolize: cp -f /opt/local/share/libtool/build-aux/install-sh build/build-aux
glibtoolize: cp -f /opt/local/share/libtool/build-aux/ltmain.sh build/build-aux
glibtoolize: found 'Makefile.am'
glibtoolize: aclocal_amflags=-I m4'
glibtoolize: am_macro_dir='m4'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: cp -f /opt/local/share/aclocal/libtool.m4 m4
glibtoolize: Not copying 'm4/ltargz.m4', libltdl not used.
glibtoolize: Not copying 'm4/ltdl.m4', libltdl not used.
glibtoolize: cp -f /opt/local/share/aclocal/ltoptions.m4 m4
glibtoolize: cp -f /opt/local/share/aclocal/ltsugar.m4 m4
glibtoolize: cp -f /opt/local/share/aclocal/ltversion.m4 m4
glibtoolize: cp -f /opt/local/share/aclocal/lt~obsolete.m4 m4
glibtoolize: found LT_INIT invocation
`/opt/local/bin/autoreconf --install --force --verbose' 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --install --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: true --copy --force
autoreconf: running: /opt/local/bin/autoconf --force
autoreconf: running: /opt/local/bin/autoheader --force
autoreconf: running: /opt/local/bin/automake --add-missing --copy --force-missing
configure.ac:22: installing 'build/build-aux/compile'
configure.ac:16: installing 'build/build-aux/missing'
Makefile.am: installing 'build/build-aux/depcomp'
autoreconf: Leaving directory `.'
./bootstrap.sh: line 363: popd: directory stack empty
checking build system type... x86_64-apple-darwin18.2.0
checking host system type... x86_64-apple-darwin18.2.0
checking target system type... x86_64-apple-darwin18.2.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... build/build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether /usr/bin/make sets $(MAKE)... yes
checking whether /usr/bin/make supports nested variables... yes
checking whether UID '502' is supported by ustar format... yes
checking whether GID '20' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether /usr/bin/make supports the include directive... yes (GNU style)
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking whether clang understands -c and -o together... yes
checking dependency style of clang... gcc3
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether /usr/bin/make supports nested variables... (cached) yes
checking for pkg-config... no
checking for openssl/ssl.h in /usr/local/ssl... no
checking for openssl/ssl.h in /usr/lib/ssl... no
checking for openssl/ssl.h in /usr/ssl... no
checking for openssl/ssl.h in /usr/pkg... no
checking for openssl/ssl.h in /usr/local... no
checking for openssl/ssl.h in /usr... no
checking whether compiling and linking against OpenSSL works... no
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by clang... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin18.2.0 file names to x86_64-apple-darwin18.2.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin18.2.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from clang object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if clang supports -fno-rtti -fno-exceptions... yes
checking for clang option to produce PIC... -fno-common -DPIC
checking if clang PIC flag -fno-common -DPIC works... yes
checking if clang static flag -static works... no
checking if clang supports -c -o file.o... yes
checking if clang supports -c -o file.o... (cached) yes
checking whether the clang linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.2.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking dependency style of clang++... gcc3
checking how to run the C++ preprocessor... clang++ -E
checking for ld used by clang++... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking whether the clang++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking for clang++ option to produce PIC... -fno-common -DPIC
checking if clang++ PIC flag -fno-common -DPIC works... yes
checking if clang++ static flag -static works... no
checking if clang++ supports -c -o file.o... yes
checking if clang++ supports -c -o file.o... (cached) yes
checking whether the clang++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.2.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether clang++ accepts -g... (cached) yes
checking dependency style of clang++... (cached) gcc3
checking for gcc... (cached) clang
checking whether we are using the GNU C compiler... (cached) yes
checking whether clang accepts -g... (cached) yes
checking for clang option to accept ISO C89... (cached) none needed
checking whether clang understands -c and -o together... (cached) yes
checking dependency style of clang... (cached) gcc3
checking for clang option to accept ISO C99... none needed
checking whether the linker accepts ... yes
configure: adding automake macro support
configure: creating aminclude.am
checking for debug... no
checking for vcs system... git
checking for vcs checkout... yes
checking for assert... yes
checking whether clang++ supports C++11 features by default... no
checking whether clang++ supports C++11 features with -std=gnu++11... yes
checking for location of cstdint... <cstdint>
<cstdint>
checking for location of cinttypes... <cinttypes>
<cinttypes>
checking for MSG_NOSIGNAL... 
checking for MSG_DONTWAIT... yes
checking for MSG_MORE... 
checking for latex... no
checking for elatex... no
checking for lambda... no
configure: WARNING: Unable to find the latex application
checking for pdflatex... no
configure: WARNING: Unable to find the pdflatex application
checking for kpsewhich... no
configure: WARNING: Unable to find the kpsewhich application
checking whether sphinx-build executable path has been provided... no
checking for sphinx-build... :
checking whether the compiler supports GCC C++ ABI name demangling... yes
checking checking for cxx_gcc_abi_demangle... "yes"
checking for /tmp/dummy1_zlib.h... yes
checking for library containing gzopen... -lz
checking cxxabi.h usability... yes
checking cxxabi.h presence... yes
checking for cxxabi.h... yes
checking argp.h usability... no
checking argp.h presence... no
checking for argp.h... no
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking io.h usability... no
checking io.h presence... no
checking for io.h... no
checking openssl/ssl.h usability... no
checking openssl/ssl.h presence... no
checking for openssl/ssl.h... no
checking poll.h usability... yes
checking poll.h presence... yes
checking for poll.h... yes
checking pwd.h usability... yes
checking pwd.h presence... yes
checking for pwd.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking winsock2.h usability... no
checking winsock2.h presence... no
checking for winsock2.h... no
checking ws2tcpip.h usability... no
checking ws2tcpip.h presence... no
checking for ws2tcpip.h... no
checking which socket options are supported... checking whether SO_KEEPALIVE is supported... no
checking whether TCP_KEEPCNT is supported... no
checking whether TCP_KEEPIDLE is supported... no
checking whether TCP_KEEPINTVL is supported... no
checking whether TCP_KEEPALIVE is supported... no
checking for in_port_t... yes
checking for ssize_t... yes
checking for size_t... yes
checking for fcntl... yes
checking for on_exit... no
checking for poll... yes
checking for ppoll... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... -D_THREAD_SAFE
checking for PTHREAD_PRIO_INHERIT... yes
checking whether byte ordering is bigendian... no
checking if all warnings into errors... yes
checking for C compiler vendor... clang
checking C Compiler version... "Apple LLVM version 10.0.0 (clang-1000.11.45.5)"
checking C++ Compiler version... "Apple LLVM version 10.0.0 (clang-1000.11.45.5)"
checking MINGW... checking whether __MINGW32__ is declared... no
no
checking whether the -Werror option is usable... yes
checking for simple visibility declarations... yes
checking whether C compiler accepts ... yes
checking whether C compiler accepts -g... yes
checking whether C compiler accepts -O2... yes
checking whether C compiler accepts -fstack-check... yes
checking whether C compiler accepts -Wpragmas... yes
checking whether C compiler accepts -Wunknown-pragmas... yes
checking whether C compiler accepts -Qunused-arguments... yes
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -Wextra... yes
checking whether C compiler accepts -Weverything... no
checking whether C compiler accepts -Wthis-test-should-fail... no
checking whether C compiler accepts -Wunsuffixed-float-constants... no
checking whether C compiler accepts -Wjump-misses-init... no
checking whether C compiler accepts -Wno-attributes... yes
checking whether C compiler accepts -Waddress... yes
checking whether C compiler accepts -Wvarargs... yes
checking whether C compiler accepts -Warray-bounds... yes
checking whether C compiler accepts -Wbad-function-cast... yes
checking whether C compiler accepts -Wchar-subscripts... yes
checking whether C compiler accepts -Wcomment... yes
checking whether C compiler accepts -Wfloat-equal... yes
checking whether C compiler accepts -Wformat-security... yes
checking whether C compiler accepts -Wformat=2... yes
checking whether C compiler accepts -Wformat-y2k... yes
checking whether C compiler accepts -Wlogical-op... no
checking whether C compiler accepts -Wmaybe-uninitialized... no
checking whether C compiler accepts -Wmissing-field-initializers... yes
checking whether C compiler accepts -Wmissing-noreturn... yes
checking whether C compiler accepts -Wmissing-prototypes... yes
checking whether C compiler accepts -Wnested-externs... yes
checking whether C compiler accepts -Wnormalized=id... no
checking whether C compiler accepts -Woverride-init... no
checking whether C compiler accepts -Wpointer-arith... yes
checking whether C compiler accepts -Wpointer-sign... yes
checking whether C compiler accepts -Wredundant-decls... yes
checking whether C compiler accepts -Wshadow... yes
checking whether C compiler accepts -Wshorten-64-to-32... yes
checking whether C compiler accepts -Wsign-compare... yes
checking whether C compiler accepts -Wstrict-overflow=1... yes
checking whether C compiler accepts -Wstrict-prototypes... yes
checking whether C compiler accepts -Wswitch-enum... yes
checking whether C compiler accepts -Wtrampolines... no
checking whether C compiler accepts -Wundef... yes
checking whether C compiler accepts -funsafe-loop-optimizations... no
checking whether C compiler accepts -Wclobbered... no
checking whether C compiler accepts -Wunused... yes
checking whether C compiler accepts -Wunused-result... yes
checking whether C compiler accepts -Wunused-variable... yes
checking whether C compiler accepts -Wunused-parameter... yes
checking whether C compiler accepts -Wunused-local-typedefs... yes
checking whether C compiler accepts -Wwrite-strings... yes
checking whether C compiler accepts -floop-parallelize-all... no
checking whether C compiler accepts -fwrapv... yes
checking whether C compiler accepts -fmudflapt... no
checking whether C compiler accepts -pipe... yes
checking whether C compiler accepts -fPIE... yes
checking whether C compiler accepts -pie... yes
checking whether C compiler accepts -Wsizeof-pointer-memaccess... yes
checking whether C compiler accepts -Wpacked... yes
checking whether C compiler accepts -Wlong-long... yes
checking whether C compiler accepts -Wunreachable-code... yes
checking whether C++ compiler accepts -g... yes
checking whether C++ compiler accepts -O2... yes
checking whether C++ compiler accepts -fstack-check... yes
checking whether C++ compiler accepts -Wpragmas... yes
checking whether C++ compiler accepts -Wunknown-pragmas... yes
checking whether C++ compiler accepts -Wall... yes
checking whether C++ compiler accepts -Wextra... yes
checking whether C++ compiler accepts -Weverything... no
checking whether C++ compiler accepts -Wthis-test-should-fail... no
checking whether C++ compiler accepts -Wno-attributes... yes
checking whether C++ compiler accepts -Wvarargs... yes
checking whether C++ compiler accepts -Waddress... yes
checking whether C++ compiler accepts -Warray-bounds... yes
checking whether C++ compiler accepts -Wchar-subscripts... yes
checking whether C++ compiler accepts -Wcomment... yes
checking whether C++ compiler accepts -Wctor-dtor-privacy... yes
checking whether C++ compiler accepts -Wfloat-equal... yes
checking whether C++ compiler accepts -Wformat=2... yes
checking whether C++ compiler accepts -Wformat-y2k... yes
checking whether C++ compiler accepts -Wmaybe-uninitialized... no
checking whether C++ compiler accepts -Wmissing-field-initializers... yes
checking whether C++ compiler accepts -Wlogical-op... no
checking whether C++ compiler accepts -Wnon-virtual-dtor... yes
checking whether C++ compiler accepts -Wnormalized=id... no
checking whether C++ compiler accepts -Woverloaded-virtual... yes
checking whether C++ compiler accepts -Wpointer-arith... yes
checking whether C++ compiler accepts -Wredundant-decls... yes
checking whether C++ compiler accepts -Wshadow... yes
checking whether C++ compiler accepts -Wshorten-64-to-32... yes
checking whether C++ compiler accepts -Wsign-compare... yes
checking whether C++ compiler accepts -Wstrict-overflow=1... yes
checking whether C++ compiler accepts -Wswitch-enum... yes
checking whether C++ compiler accepts -Wtrampolines... no
checking whether C++ compiler accepts -Wundef... yes
checking whether C++ compiler accepts -funsafe-loop-optimizations... no
checking whether C++ compiler accepts -Wc++11-compat... yes
checking whether C++ compiler accepts -Wclobbered... no
checking whether C++ compiler accepts -Wunused... yes
checking whether C++ compiler accepts -Wunused-result... yes
checking whether C++ compiler accepts -Wunused-variable... yes
checking whether C++ compiler accepts -Wunused-parameter... yes
checking whether C++ compiler accepts -Wunused-local-typedefs... yes
checking whether C++ compiler accepts -Wwrite-strings... yes
checking whether C++ compiler accepts -Wformat-security... yes
checking whether C++ compiler accepts -floop-parallelize-all... no
checking whether C++ compiler accepts -fwrapv... yes
checking whether C++ compiler accepts -fmudflapt... no
checking whether C++ compiler accepts -pipe... yes
checking whether C++ compiler accepts -fPIE... yes
checking whether C++ compiler accepts -pie... no
checking whether C++ compiler accepts -Wsizeof-pointer-memaccess... yes
checking whether C++ compiler accepts -Wpacked... yes
checking whether C++ compiler accepts -Wlong-long... yes
checking whether C++ compiler accepts -Wunreachable-code... yes
checking whether C compiler accepts -I./include... yes
checking whether C compiler accepts -I.... yes
checking whether C compiler accepts -I./... yes
checking whether C compiler accepts -I./include... (cached) yes
checking whether C compiler accepts -I./include... (cached) yes
checking whether C compiler accepts -I.... (cached) yes
checking whether C compiler accepts -I./... (cached) yes
checking whether C compiler accepts -I./include... (cached) yes
creating libdrizzle-redux6-config - generic 6.1.4 for -ldrizzle-redux6
checking the number of available CPUs... 8 
configure: added jobserver support to make for 9 jobs
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating docs/conf.py
config.status: creating pkg/rpm/spec
config.status: creating include/libdrizzle-redux/version.h
config.status: creating api-sanity-checker-version.xml
config.status: creating pkg/deb/build
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
---
Configuration summary for libdrizzle-redux6 version 6.1.4

   * Installation prefix:       /usr/local
   * System type:               apple-darwin18.2.0
   * Host CPU:                  x86_64
   * Compiler Vendor:           clang
   * C Compiler:                clang
   * C Compiler Version:        Apple LLVM version 10.0.0 (clang-1000.11.45.5)
   * C Flags:                   -g -O2  -fstack-check -Wpragmas -Wunknown-pragmas -Qunused-arguments -Wall -Wextra -Wno-attributes -Waddress -Wvarargs -Warray-bounds -Wbad-function-cast -Wchar-subscripts -Wcomment -Wfloat-equal -Wformat-security -Wformat=2 -Wformat-y2k -Wmissing-field-initializers -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wpointer-sign -Wredundant-decls -Wshadow -Wshorten-64-to-32 -Wsign-compare -Wstrict-overflow=1 -Wstrict-prototypes -Wswitch-enum -Wundef -Wunused -Wunused-result -Wunused-variable -Wunused-parameter -Wunused-local-typedefs -Wwrite-strings -fwrapv -pipe -fPIE -pie -Wsizeof-pointer-memaccess -Wpacked -Wlong-long -Wunreachable-code -Werror -I./include -I. -I./
   * C++ Compiler:              clang++ -std=gnu++11
   * C++ Version:               Apple LLVM version 10.0.0 (clang-1000.11.45.5)
   * C++ Flags:                 -g -O2 -fstack-check -Wpragmas -Wunknown-pragmas -Wall -Wextra -Wno-attributes -Wvarargs -Waddress -Warray-bounds -Wchar-subscripts -Wcomment -Wctor-dtor-privacy -Wfloat-equal -Wformat=2 -Wformat-y2k -Wmissing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wredundant-decls -Wshadow -Wshorten-64-to-32 -Wsign-compare -Wstrict-overflow=1 -Wswitch-enum -Wundef -Wc++11-compat -Wunused -Wunused-result -Wunused-variable -Wunused-parameter -Wunused-local-typedefs -Wwrite-strings -Wformat-security -fwrapv -pipe -fPIE -Wsizeof-pointer-memaccess -Wpacked -Wlong-long -Wunreachable-code -Werror -I./include -I. -I./
   * CPP Flags:                   -fvisibility=hidden
   * LIB Flags:                 
   * Assertions enabled:        yes
   * Debug enabled:             no
   * Warnings as failure:       yes
   * make -j:                   9
   * VCS checkout:              git

---
`/usr/bin/make all' 
/usr/bin/make  all-am
  CC       tests/unit/binlog.o
  CC       tests/unit/common.o
  CXX      src/libdrizzle_redux6_la-binlog.lo
In file included from src/binlog.cc:39:
In file included from ./src/common.h:84:
./src/structs.h:252:3: error: unknown type name 'SSL_CTX'
  SSL_CTX *ssl_context;
  ^
./src/structs.h:253:3: error: unknown type name 'SSL'
  SSL *ssl;
  ^
2 errors generated.
make[1]: *** [src/libdrizzle_redux6_la-binlog.lo] Error 1
make: *** [all] Error 2
./bootstrap.sh:972: Failed to execute /usr/bin/make all

~/Desktop/libdrizzle-redux · (v6.x.x±)
```

**Comment by andreas-bok-sociomantic** [comment]
Hi. 
AFAICS the openssl library and headerrs are not found which would explain the compilation error. 

```
checking for openssl/ssl.h in /usr/local/ssl... no
checking for openssl/ssl.h in /usr/lib/ssl... no
checking for openssl/ssl.h in /usr/ssl... no
checking for openssl/ssl.h in /usr/pkg... no
checking for openssl/ssl.h in /usr/local... no
checking for openssl/ssl.h in /usr... no
checking whether compiling and linking against OpenSSL works... no
...
checking openssl/ssl.h usability... no
checking openssl/ssl.h presence... no
checking for openssl/ssl.h... no
```

Compilation using the `bootstrap.sh` script also fails on my mac, so using that to build seems to be broken. This however is also the case on `ubuntu`.

I can compile on my mac running Mojave 10.14.1 using the manual build steps: 

```
mkdir build && cd build
autoreconf -fi ..
../configure
make
```

The configuration is:

```
   * Installation prefix:       /usr/local
   * System type:               apple-darwin18.2.0
   * Host CPU:                  x86_64
   * Compiler Vendor:           clang
   * C Compiler:                clang
   * C Compiler Version:        Apple LLVM version 10.0.0 (clang-1000.11.45.5)
   * C Flags:                   -g -O2  -Wno-unknown-pragmas -Wno-pragmas -Qunused-arguments -Wall -Wextra -Wno-attributes -Waddress -Wvarargs -Warray-bounds -Wbad-function-cast -Wchar-subscripts -Wcomment -Wfloat-equal -Wformat-security -Wformat=2 -Wformat-y2k -Wmissing-field-initializers -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wpointer-sign -Wredundant-decls -Wshadow -Wshorten-64-to-32 -Wsign-compare -Wstrict-overflow=1 -Wstrict-prototypes -Wswitch-enum -Wundef -Wunused -Wunused-result -Wunused-variable -Wunused-parameter -Wunused-local-typedefs -Wwrite-strings -fwrapv -pipe -fPIE -pie -Wsizeof-pointer-memaccess -Wpacked -Wlong-long -Wunreachable-code -I../include -I.. -I./ -I./include
   
   * C++ Compiler:              clang++ -std=gnu++11
   * C++ Version:               Apple LLVM version 10.0.0 (clang-1000.11.45.5)
   * C++ Flags:                 -g -O2 -Wno-unknown-pragmas -Wno-pragmas -Wall -Wextra -Wno-attributes -Wvarargs -Waddress -Warray-bounds -Wchar-subscripts -Wcomment -Wctor-dtor-privacy -Wfloat-equal -Wformat=2 -Wformat-y2k -Wmissing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wredundant-decls -Wshadow -Wshorten-64-to-32 -Wsign-compare -Wstrict-overflow=1 -Wswitch-enum -Wundef -Wc++11-compat -Wunused -Wunused-result -Wunused-variable -Wunused-parameter -Wunused-local-typedefs -Wwrite-strings -Wformat-security -fwrapv -pipe -fPIE -Wsizeof-pointer-memaccess -Wpacked -Wlong-long -Wunreachable-code -I../include -I.. -I./ -I./include
   * CPP Flags:                 -I/usr/local/include  -fvisibility=hidden
   * LIB Flags:
   * Assertions enabled:        no
   * Debug enabled:             no
   * Warnings as failure:       no
   * make -j:                   5
   * VCS checkout:              none
```

**Comment by bokchan** [comment]
Closing as no further details on the problem has been reported
